class_name AttributeTalentCatalog

## Talente laut Ressources/Charakterbogen.md — pro Attribut.

const ENTRIES: Array[Dictionary] = [
	{
		"skill_id": "waffenloser_kampf",
		"skill_name": "Waffenloser Kampf",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "hiebwaffenfuehrung",
		"skill_name": "Hiebwaffenführung",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "ringen_grifftechniken",
		"skill_name": "Ringen & Grifftechniken",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "heben_tragen",
		"skill_name": "Heben & Tragen schwerer Lasten",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "belagerungsgeraet",
		"skill_name": "Belagerungsgerät bedienen",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "nahkampf_exoskelette",
		"skill_name": "Nahkampf mit Exoskeletten",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "schwertkampf_klassisch",
		"skill_name": "Schwertkampf (klassisch)",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "axtwerfen",
		"skill_name": "Axtwerfen",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "koerperliche_zaehigkeit",
		"skill_name": "Körperliche Zähigkeit (Schmerzresistenz)",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "kickboxen_martial_arts",
		"skill_name": "Kickboxen / Martial Arts",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "turmspringen_weitsprung",
		"skill_name": "Turmspringen / Weitsprung",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "panzerplatten_oeffnen",
		"skill_name": "Panzerplatten öffnen (Sci-Fi)",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "brechstangen_technik",
		"skill_name": "Brechstangen-Technik",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "schwimmen_gegen_stroemungen",
		"skill_name": "Schwimmen gegen Strömungen",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "zweihandwaffen",
		"skill_name": "Zweihandwaffen (Hammer, Zweihänder)",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "fahrzeugreparatur_kraft",
		"skill_name": "Fahrzeugreparatur mit Muskelkraft (z. B. Panzerketten)",
		"beschreibung": "Talent der Körperkraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.KOERPERKRAFT,
	},
	{
		"skill_id": "ausdauerlauf_marathon",
		"skill_name": "Ausdauerlauf / Marathon",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "widerstand_gifte",
		"skill_name": "Widerstand gegen Gifte",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "kaelte_hitzetoleranz",
		"skill_name": "Kälte- und Hitzetoleranz",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "fasten_ueberleben",
		"skill_name": "Fasten & Überleben ohne Nahrung",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "ruestungstragen",
		"skill_name": "Rüstungstragen (Schwere Rüstung, Raumanzüge)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "meditation_regeneration",
		"skill_name": "Meditation zur Regeneration",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "bergsteigen_extrem",
		"skill_name": "Bergsteigen unter Extrembedingungen",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "resistenz_strahlung",
		"skill_name": "Resistenz gegen Strahlung (Sci-Fi)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "wundheilung_beschleunigen",
		"skill_name": "Wundheilung beschleunigen (durch Training oder Geisttechniken)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "tauchen_ohne_atmung",
		"skill_name": "Tauchen ohne Atemgerät",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "schlafreduktion",
		"skill_name": "Schlafreduktion (weniger Schlaf, volle Leistung)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "immunstaerkung",
		"skill_name": "Immunstärkung (Heilkunst, Kräuter, Nanomedizin)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "kampftauchen",
		"skill_name": "Kampftauchen (mit voller Ausrüstung)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "sturzresistenz",
		"skill_name": "Sturzresistenz (Abrollen, Knochenfestigkeit)",
		"beschreibung": "Talent der Robustheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.ROBUSTHEIT,
	},
	{
		"skill_id": "tai_chi_qi_gong",
		"skill_name": "Tai-Chi / Qi Gong",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "akrobatik",
		"skill_name": "Akrobatik (Salti, Sprünge, Balance)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "klettern",
		"skill_name": "Klettern (urban & Felsen)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "parkour",
		"skill_name": "Parkour / Freerunning",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "fechten",
		"skill_name": "Fechten",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "bogenschiessen",
		"skill_name": "Bogenschießen",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "schleichen_tarnen",
		"skill_name": "Schleichen & Tarnen",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "fliegen_luftfahrzeuge",
		"skill_name": "Fliegen kleiner Luftfahrzeuge (Gleiter, Jetpacks)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "reiten_alien_tiere",
		"skill_name": "Reiten / Alien-Tiere lenken",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "messerwerfen",
		"skill_name": "Messerwerfen",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "drohnensteuerung",
		"skill_name": "Drohnensteuerung",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "reflextraining",
		"skill_name": "Reflextraining (schnelle Reaktionen)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "jonglage_feinmotorik",
		"skill_name": "Jonglage / Feinmotorik",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "taenze",
		"skill_name": "Tänze (Kampftanz, Ritualtanz, Cyberdance)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "schwertkunst_leichtwaffen",
		"skill_name": "Schwertkunst mit Leichtwaffen (Rapier, Lichtschwert)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "pilotenmanoever",
		"skill_name": "Pilotenmanöver (Sci-Fi Raumjäger)",
		"beschreibung": "Talent der Gewandheit. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.GEWANDHEIT,
	},
	{
		"skill_id": "magiekunde",
		"skill_name": "Magiekunde (Arkan, Elementar, Illusion)",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "alchemie",
		"skill_name": "Alchemie",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "heilkunde_medizin",
		"skill_name": "Heilkunde / Medizin",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "astronomie_navigation",
		"skill_name": "Astronomie & Navigation",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "sprachwissenschaft",
		"skill_name": "Sprachwissenschaft (Alte Runen, Alien-Sprachen, KI-Codes)",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "ingenieurskunst",
		"skill_name": "Ingenieurskunst (klassisch & futuristisch)",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "mechanik_feinmechanik",
		"skill_name": "Mechanik / Feinmechanik",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "kryptografie",
		"skill_name": "Kryptografie / Codeknacken",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "biologie",
		"skill_name": "Biologie (Pflanzen, Tiere, Xenobiologie)",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "physik",
		"skill_name": "Physik (Ballistik, Gravitation, Energie)",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "programmieren_hacking",
		"skill_name": "Programmieren / Hacking",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "strategie_taktik",
		"skill_name": "Strategie & Taktik",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "architektur_staedtebau",
		"skill_name": "Architektur / Städtebau",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "geschichte_kulturkunde",
		"skill_name": "Geschichte & Kulturkunde",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "theologie_okkultismus",
		"skill_name": "Theologie & Okkultismus",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "nanotechnologie",
		"skill_name": "Nanotechnologie (Sci-Fi)",
		"beschreibung": "Talent der Verstand. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.VERSTAND,
	},
	{
		"skill_id": "schmerzresistenz_mental",
		"skill_name": "Schmerzresistenz (mentale Ebene)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "meditation_trance",
		"skill_name": "Meditation / Trance",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "hypnose_widerstehen",
		"skill_name": "Hypnose widerstehen",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "telepathie_widerstehen",
		"skill_name": "Telepathie widerstehen",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "konzentration_gefecht",
		"skill_name": "Konzentration in Gefecht & Chaos",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "oath_keeping",
		"skill_name": "Oath-Keeping (Schwüre halten, auch unter Folter)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "rausch_resistenz",
		"skill_name": "Rausch-Resistenz (Alkohol, Drogen, Betäubungsgase)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "fokussierte_wut",
		"skill_name": "Fokussierte Wut (Kampfrausch)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "illusionsresistenz",
		"skill_name": "Illusionsresistenz (Magie oder VR)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "astralprojektion",
		"skill_name": "Astralprojektion / Klartraumkontrolle",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "durchhalten_schlafentzug",
		"skill_name": "Durchhalten bei Schlafentzug",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "cybernetic_override",
		"skill_name": "Cybernetic Override (künstliche Implantate mental steuern)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "geistesblitz",
		"skill_name": "Geistesblitz (Eingebungen erzwingen)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "suggestion_widerstehen",
		"skill_name": "Suggestion widerstehen",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "panikresistenz",
		"skill_name": "Panikresistenz (Terror, Cthulhu-Style Wesen, Alien-Begegnung)",
		"beschreibung": "Talent der Willenskraft. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.WILLENSKRAFT,
	},
	{
		"skill_id": "rhetorik_ueberzeugen",
		"skill_name": "Rhetorik / Überzeugen",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "diplomatie_verhandlung",
		"skill_name": "Diplomatie & Verhandlung",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "einschuechtern",
		"skill_name": "Einschüchtern (Körperhaltung, Stimme, Präsenz)",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "schauspielerei_taeuschung",
		"skill_name": "Schauspielerei / Täuschung",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "fuehrungsqualitaet",
		"skill_name": "Führungsqualität (Motivieren, Befehligen)",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "magische_aura",
		"skill_name": "Magische Aura (Ausstrahlung im Okkulten)",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "charisma_digital",
		"skill_name": "Charisma im digitalen Raum (Influencer, Propaganda)",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "luegen_manipulation",
		"skill_name": "Lügen & Manipulation",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "verfuehrung",
		"skill_name": "Verführung",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "predigen_inspirieren",
		"skill_name": "Predigen / Inspirieren",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "schauspiel_maskenspiel",
		"skill_name": "Schauspiel & Maskenspiel (auch Sci-Fi Hologramme)",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "bardenkunst",
		"skill_name": "Bardenkunst / Musik / Performance",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "kommando_schlachtfeld",
		"skill_name": "Kommando auf Schlachtfeld",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "koerpersprache",
		"skill_name": "Körpersprache deuten & einsetzen",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "propaganda_medien",
		"skill_name": "Propaganda / Medienkontrolle",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "psychologische_gespraechsfuehrung",
		"skill_name": "Psychologische Gesprächsführung",
		"beschreibung": "Talent der Präsenz. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.PRAESENZ,
	},
	{
		"skill_id": "intuition",
		"skill_name": "Intuition",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "gefahrensinn",
		"skill_name": "Gefahrensinn (präventives Wahrnehmen)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "omen_lesen",
		"skill_name": "Omen lesen / Weissagung",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "astralsicht",
		"skill_name": "Astralsicht / sechster Sinn",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "wachtraeumen_klartraeumen",
		"skill_name": "Wachträumen / Klarträumen",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "meditation_achtsamkeit",
		"skill_name": "Meditation & Achtsamkeit",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "scanner_nutzung",
		"skill_name": "Scanner-Nutzung (Sci-Fi Geräte, magische Kristalle)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "wahrnehmungsschaerfung",
		"skill_name": "Wahrnehmungsschärfung (Geräusche, Gerüche, Licht)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "multitasking",
		"skill_name": "Multitasking (mehrere Dinge gleichzeitig fokussiert halten)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "ueberwachungskunst",
		"skill_name": "Überwachungskunst (Sicherheitskameras, magische Spiegel)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "cyber_awareness",
		"skill_name": "Cyber Awareness (Gefahren in der Matrix / VR erkennen)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "empathie",
		"skill_name": "Empathie (Gefühle anderer spüren)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "taktisches_bewusstsein",
		"skill_name": "Taktisches Bewusstsein (Umgebungsanalyse im Kampf)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "meditation_reinheit",
		"skill_name": "Meditation auf Reinheit des Geistes (Illusionsbrechung)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
	{
		"skill_id": "instinktorientierung",
		"skill_name": "Instinktorientierung (handeln ohne bewusstes Nachdenken)",
		"beschreibung": "Talent der Bewusstsein. Steigert das zugehörige Attribut durch Training.",
		"attribute": CharacterEnums.Attribute.BEWUSSTSEIN,
	},
]


static func create_definition(entry: Dictionary) -> SkillDefinition:
	var definition := SkillDefinition.new()
	definition.skill_id = entry.get("skill_id", "")
	definition.skill_name = entry.get("skill_name", "")
	definition.beschreibung = entry.get("beschreibung", "")
	definition.attribute = entry.get("attribute", CharacterEnums.Attribute.KOERPERKRAFT)
	return definition


static func get_entries_for_attribute(attr: CharacterEnums.Attribute) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for entry in ENTRIES:
		if entry.get("attribute") == attr:
			result.append(entry)
	return result
